### ISSUE TITLE
has_phone passes for invalid phone numbers

### ISSUE THREAD

**Issue by HawkiesZA** [turnhub/expression#224]
We've been testing out `has_phone` in some of our flows and noticed that it's quite liberal in what passes for a phone number. In the [code](https://github.com/turnhub/expression/blob/b350dad62960ebbbb3b3b6295c6f25cdda90975c/lib/expression/callbacks/standard.ex#L1610-L1646) it seems that it's just parsing and formatting the given number and not actually calling `is_possible_number` and `is_valid_number` on it. This means that people can basically input anything with 2 or more digits and it will "validate" as a phone number.

**Comment by smn** [comment]
I think #225 fixes it. It'll be part of the next release.
